root = "."
tmp_dir = "tmp"

[build]
# List of files to watch
cmd = "go build -o ./tmp/main ./cmd/api/main.go"
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "yaml", "yml"]
exclude_dir = ["assets", "tmp", "vendor", "postgres-data"]
include_dir = []
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
delay = 1000
stop_on_error = true
log = "build-errors.log"
send_interrupt = false
kill_delay = "0s"

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true