app:
  name: "go-web"
  version: "1.0.0"
  port: 8085
  env: "development"
  log:
    level: "debug"
    format: "json"

middleware:
  cors:
    enabled: true
    allowOrigins: ["*"]
    allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowHeaders: ["*"]
    exposeHeaders: ["*"]
    maxAge: 0
    allowCredentials: false
  csrf:
    enabled: false
    key: ""
    maxAge: 0
    domain: ""