app:
  name: "go-web"
  version: "1.0.0"
  port: 8080
  env: "development"
  log:
    level: "debug"

http:
  readTimeout: 30
  writeTimeout: 30
  idleTimeout: 30
  maxHeaderBytes: 1

database:
  # driver: "mysql" or "postgresql"
  driver: "postgresql"
  # use host: "db" if you are using docker-compose
  host: "db"
  port: 5432
  user: "root"
  password: "root"
  name: "go_web"
  # Put SSL Mode to require for production environments
  sslMode: "disable"

middleware:
  cors:
    enabled: true
    allowOrigins: ["*"]
    allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowHeaders: ["*"]
    exposeHeaders: ["*"]
    maxAge: 0
    allowCredentials: false
  csrf:
    enabled: false
    key: ""
    maxAge: 0
    domain: ""

monitoring:
  telemetry:
    enabled: true
    otlp_endpoint: "otlp.eu01.nr-data.net:4317"
    otlp_headers:
      api-key: "eu01xx1954fd86db7afa2df00d5db584FFFFNRAL"
    otlp_compression: "gzip"
    otlp_queue_size: 4094
    otlp_max_batch_size: 1024
    otlp_insecure: false
    otlp_timeout: 30