app:
  name: "go-web"
  version: "1.0.0"
  port: 8080
  env: "development"
  log:
    level: "debug"

http:
  readTimeout: 30
  writeTimeout: 30
  idleTimeout: 30
  maxHeaderBytes: 1

database:
  # driver: "mysql" or "postgresql"
  driver: "postgresql"
  # use host: "db" if you are using docker-compose
  host: "db"
  port: 5432
  user: "root"
  password: "root"
  name: "go_web"
  # Put SSL Mode to require for production environments
  sslMode: "disable"

middleware:
  cors:
    enabled: true
    allowOrigins: ["*"]
    allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowHeaders: ["*"]
    exposeHeaders: ["*"]
    maxAge: 0
    allowCredentials: false
  csrf:
    enabled: false
    key: ""
    maxAge: 0
    domain: ""